[build]
root = "backend"           
builder = "NIXPACKS"

[deploy]
startCommand = "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"

[build.nixpacks]
providers = ["python"]